apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-open-feature-operator-system/open-feature-operator-serving-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-v1alpha1-featureflagconfiguration
  failurePolicy: Fail
  name: validate.featureflagconfiguration.openfeature.dev
  rules:
  - apiGroups:
    - core.openfeature.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflagconfigurations
  sideEffects: None