apiVersion: v1
kind: Service
metadata:
  name: openfeature-nest-example-service
spec:
  type: NodePort
  selector:
    app: openfeature-nest-example
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 30000
      targetPort: 3000
      nodePort: 30000
