apiVersion: core.openfeature.dev/v1alpha3
kind: FlagSourceConfiguration
metadata:
  labels:
    app.kubernetes.io/name: flagsourceconfiguration
    app.kubernetes.io/instance: flagsourceconfiguration-sample
    app.kubernetes.io/part-of: open-feature-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: open-feature-operator
  name: flagsourceconfiguration-sample
spec:
  # TODO(user): Add fields here
