# import the default deployment as the base
bases:
  - ../../default

# replace the default namespace with {{ include "chart.namespace" . }}
# .Release.Namespace has not been used so that a custom _helpers.tpl file can maintain the expected behaviour of
# helm install -n
namespace: |-
  {{ include "chart.namespace" . }}

# merge the exclude-ns.yaml with the existing namespace definition, this contains the `$patch: delete` directive allowing 
# for the helm chart to define the namespace conditionally (only deploys when no namespace is provided and the default 
# (open-feature-operator-system) is used
patchesStrategicMerge:
  - exclude-ns.yaml
  - manager.yaml
  - exclude-webhook-server-container-port.yaml
  - exclude-validatingwebhook.yaml
  - mutatingwebhook.yaml

configMapGenerator:
- name: manager-config
  behavior: merge
  files:
    - controller_manager_config.yaml
