---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: featureflags.core.openfeature.dev
spec:
  group: core.openfeature.dev
  names:
    kind: FeatureFlag
    listKind: FeatureFlagList
    plural: featureflags
    shortNames:
    - ff
    singular: featureflag
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: FeatureFlag is the Schema for the featureflags API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: FeatureFlagSpec defines the desired state of FeatureFlag
            properties:
              flagSpec:
                description: FlagSpec is the structured representation of the feature
                  flag specification
                properties:
                  $evaluators:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  flags:
                    additionalProperties:
                      properties:
                        defaultVariant:
                          type: string
                        state:
                          enum:
                          - ENABLED
                          - DISABLED
                          type: string
                        targeting:
                          description: Targeting is the json targeting rule
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        variants:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                      required:
                      - defaultVariant
                      - state
                      - variants
                      type: object
                    type: object
                required:
                - flags
                type: object
            type: object
          status:
            description: FeatureFlagStatus defines the observed state of FeatureFlag
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - name: v1beta2
    schema:
      openAPIV3Schema:
        description: FeatureFlag is the Schema for the featureflags API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: FeatureFlagSpec defines the desired state of FeatureFlag
            properties:
              flagSpec:
                description: FlagSpec is the structured representation of the feature
                  flag specification
                properties:
                  $evaluators:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  flags:
                    additionalProperties:
                      properties:
                        defaultVariant:
                          type: string
                        state:
                          enum:
                          - ENABLED
                          - DISABLED
                          type: string
                        targeting:
                          description: Targeting is the json targeting rule
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        variants:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                      required:
                      - defaultVariant
                      - state
                      - variants
                      type: object
                    type: object
                required:
                - flags
                type: object
            type: object
          status:
            description: FeatureFlagStatus defines the observed state of FeatureFlag
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
